fos_user:
    #resource: "@FOSUserBundle/Resources/config/routes/routing.yml"
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: App\Entity\User
    from_email:
        address: "vincent@vfac.fr"
        sender_name: "vincent@vfac.fr"